language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-support 
    - extra-android-m2repository 
  licenses:
    - '.+'

before_script:
  - chmod +x ./WorkoutTracker2.0/gradlew

script:
  - ./WorkoutTracker2.0/gradlew build