language: android

jdk:
 - oraclejdk8

android:
  #adsnfjasdnf
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-support # because I'm use support library
    - extra-android-m2repository # because I'm use support library
  licenses:
    - '.+'

before_script:
  - chmod +x ./WorkoutTracker2.0 gradlew

script:
  - ./WorkoutTracker2.0 gradlew build