language: android
jdk:
 - oraclejdk8
install: ant deps
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - platform-tools
     - tools
     - android-25
     - build-tools-25.0.2
   licenses:
    - '.+'
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_script:
  - chmod +x ./WorkoutTracker2.0/gradlew
script:
  - ./WorkoutTracker2.0/gradlew build
   
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
    
notifications:
  email: false
